import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  container: {
    position: "fixed",
    zIndex: 99999,
    fontFamily:
      'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace',
    fontSize: "13px",
  },
  trigger: {
    background: "#1a1a2e",
    color: "#e0e0e0",
    border: "1px solid #333",
    borderRadius: "8px",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "12px",
    fontFamily: "inherit",
    boxShadow: "0 2px 8px rgba(0,0,0,0.3)",
  },
  panel: {
    width: "360px",
    maxHeight: "520px",
    overflowY: "auto" as const,
    background: "#1a1a2e",
    color: "#e0e0e0",
    border: "1px solid #333",
    borderRadius: "12px",
    boxShadow: "0 4px 24px rgba(0,0,0,0.4)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 16px",
    borderBottom: "1px solid #333",
  },
  headerTitle: {
    fontWeight: 600,
    fontSize: "14px",
    color: "#fff",
  },
  closeButton: {
    background: "transparent",
    color: "#888",
    border: "none",
    cursor: "pointer",
    fontSize: "16px",
    padding: "0 4px",
    fontFamily: "inherit",
  },
  section: {
    padding: "12px 16px",
    borderBottom: "1px solid #2a2a3e",
  },
  sectionTitle: {
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    color: "#888",
    marginBottom: "8px",
    letterSpacing: "0.5px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  templateGrid: {
    display: "flex",
    gap: "6px",
    flexWrap: "wrap" as const,
  },
  templateButton: {
    background: "#2a2a3e",
    color: "#a0c4ff",
    border: "1px solid #3a3a5e",
    borderRadius: "6px",
    padding: "4px 10px",
    cursor: "pointer",
    fontSize: "12px",
    fontFamily: "inherit",
  },
  searchInput: {
    width: "100%",
    background: "#2a2a3e",
    color: "#e0e0e0",
    border: "1px solid #3a3a5e",
    borderRadius: "6px",
    padding: "6px 10px",
    fontSize: "12px",
    marginBottom: "8px",
    fontFamily: "inherit",
    boxSizing: "border-box" as const,
  },
  userList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
  },
  userRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "6px 8px",
    background: "#2a2a3e",
    borderRadius: "6px",
  },
  userInfo: {
    flex: 1,
    minWidth: 0,
  },
  userLabel: {
    fontWeight: 500,
    color: "#fff",
    fontSize: "13px",
  },
  userEmail: {
    color: "#888",
    fontSize: "11px",
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
  },
  loginButton: {
    background: "#3a5a8a",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    padding: "4px 10px",
    cursor: "pointer",
    fontSize: "11px",
    fontFamily: "inherit",
    marginLeft: "8px",
    flexShrink: 0,
  },
  sessionFields: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
  },
  fieldRow: {
    display: "flex",
    justifyContent: "space-between",
    padding: "4px 8px",
    background: "#2a2a3e",
    borderRadius: "4px",
  },
  fieldKey: {
    color: "#a0c4ff",
    fontWeight: 500,
  },
  fieldValue: {
    color: "#e0e0e0",
    textAlign: "right" as const,
    maxWidth: "60%",
    overflow: "hidden" as const,
    textOverflow: "ellipsis" as const,
    whiteSpace: "nowrap" as const,
  },
  editFieldRow: {
    marginBottom: "8px",
  },
  editFieldLabel: {
    display: "block",
    fontSize: "11px",
    color: "#888",
    marginBottom: "4px",
  },
  editInput: {
    width: "100%",
    background: "#2a2a3e",
    color: "#e0e0e0",
    border: "1px solid #3a3a5e",
    borderRadius: "4px",
    padding: "6px 8px",
    fontSize: "12px",
    fontFamily: "inherit",
    boxSizing: "border-box" as const,
  },
  saveButton: {
    width: "100%",
    background: "#3a8a5a",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    padding: "8px",
    cursor: "pointer",
    fontSize: "12px",
    fontFamily: "inherit",
    marginTop: "4px",
  },
  refreshButton: {
    background: "transparent",
    color: "#a0c4ff",
    border: "none",
    cursor: "pointer",
    fontSize: "11px",
    fontFamily: "inherit",
    padding: "0",
  },
  errorBanner: {
    background: "#3a1a1a",
    color: "#ff8080",
    padding: "8px 16px",
    fontSize: "12px",
    borderBottom: "1px solid #4a2a2a",
  },
  errorText: {
    color: "#ff8080",
    fontSize: "12px",
  },
  muted: {
    color: "#666",
    fontSize: "12px",
    fontStyle: "italic" as const,
  },
};
